name: Terraform Apply on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  terraform-apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ${GITHUB_WORKSPACE}/kubeconfig
          echo "KUBECONFIG_PATH=${GITHUB_WORKSPACE}/kubeconfig" >> $GITHUB_ENV

      - name: Verify Kubeconfig Path
        run: |
          echo "Checking if kubeconfig file exists at ${GITHUB_WORKSPACE}/kubeconfig"
          ls -l ${GITHUB_WORKSPACE}/kubeconfig

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_kubeconfig_path: ${{ env.KUBECONFIG_PATH }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
